name: CI with GitHub Actions
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: PWD
        run: |
          pwd
          ls -altr
      - name: Upload Articfact
        uses: actions/upload-artifact@v3
        with:
         name: buildArtifact
         path: target/*.war    
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: buildArtifact
      - run: ls -altr
