
name: Testing Variables
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:  
env: 
  x: 5
  y: 3

jobs:
  dummy_job:

    # if: github.GITHUB_REF_NAME == 'master'
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $github.ref_name
          echo $(($x + $y))
